<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/27
 * Time: 11:56
 */
namespace app\store\controller;

use think\Db;
use think\Request;

Class File extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->auth();
    }

    public function index(){

        $list = Db::name('file')
            ->alias('f')
            ->join('goods g','g.goods_id = f.goods_id')
            ->join('category c','c.category_id = g.category_id')
            ->field('f.*,g.goods_name as goods_name,c.name as category_name')
            ->paginate(10,false,['query'=>Request::instance()->request()]);
//        dump($list);
        return $this->fetch('index',compact('list'));
    }

    public function add(){
        $goods = Db::name('category')->select();

        $cate = [];
        foreach($goods as $k => $v){
            $v['sub'] = Db::name('goods')
                ->where('category_id',$v['category_id'])
                ->select();
            $cate[] = $v;
        }

        return $this->fetch('add',compact('cate'));
    }

    public function doadd(){
        if(request()->isPost()){

            $res = Request::instance()->except('file');
            $res['addtime'] = time();
            $res['file'] = $this->upload();

            $data = Db::name('file')->insert($res);

            if($data){
                return $this->return_msg(200,'成功');
            }else{
                return $this->return_msg(400,'error');
            }
        }
    }

    public function edit(){
        $id = input('id');
        $goods = Db::name('category')->select();

        $cate = [];
        foreach($goods as $k => $v){
            $v['sub'] = Db::name('goods')
                ->where('category_id',$v['category_id'])
                ->select();
            $cate[] = $v;
        }
        $edit = Db::name('file')->find($id);
        return $this->fetch('edit',compact('edit','cate'));
    }

    public function doedit(){

        if(request()->isPost()){
            $res = Request::instance()->except('file');

            $file = $this->upload();

            if($file){
                $info = Db::name('file')->find($res['id']);

                if($info['file']){
                    $url = str_replace('/uploads','uploads',$info['file']);

                    if(file_exists($url)){
                        unlink($url);
                    }
                }
                $res['file'] = $file;
            }

            $data = Db::name('file')->update($res);

            if($data){
                return $this->return_msg(200,'修改成功');
            }else{
                return $this->return_msg(400,'error');
            }
        }
    }
    public function del(){
        $id = input('id');

        $info = Db::name('file')->find($id);

        if($info['file']){
            $url = str_replace('/uploads','uploads',$info['file']);
            if(file_exists($url)){
                unlink($url);
            }
        }
        $data = Db::name('file')->delete($id);

        if($data){
            return $this->index();
        }
    }
    public function upload(){

        $file = request()->file('file');

        if($file){
            $info = $file->validate(['ext' => 'pdf','size' => 20000000])->move(ROOT_PATH.'../web'.DS.'uploads');

            if($info){
                return DS.'uploads'.DS.$info->getSaveName();
            }else{
                return $this->return_msg(400,$file->getError());
            }
        }
    }
}