<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/7/3
 * Time: 14:26
 */
namespace app\store\controller;

use think\Db;
use think\Request;

Class Finance extends Controller{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->auth();
    }
    public function index(){

        if($this->store['user']['rid'] != 0){
            $user_id = $this->store['user']['store_user_id'];

            $info = Db::name('user')->where('parent_id',$user_id)->field('user_id')->select();

            $arr = [];
            foreach($info as $v){
                $arr[] = $v['user_id'];

            }
            $str = implode(',',$arr);

            $order = Db::name('order')
                ->alias('o')
                ->where('o.user_id',$str)
                ->order('create_time desc')
                ->join('order_goods og','og.order_id = o.order_id')
                ->join('goods g','g.goods_id = og.goods_id')
                ->join('goods_spec gs','gs.goods_id = g.goods_id')
                ->join('goods_image img','img.goods_id = g.goods_id')
                ->join('upload_file u','u.file_id = img.image_id')
                ->join('user us','us.user_id = o.user_id')
                ->field('gs.goods_price,g.bonus_ratio,og.total_num,o.order_no,g.goods_name,o.goods_no,o.pay_price,o.create_time,u.file_name,us.nickName,us.avatarUrl')
                ->paginate('10',false,['query' => Request::instance()->request()]);

            $arr = [];
            foreach ($order as $o){
                $arr[] = ($o['goods_price'] * $o['total_num']) * $o['bonus_ratio']/100;
            }

            $totalprice = 0;
            foreach($arr as $a){
                $totalprice += $a;

            }

            $balance = Db::name('store_user')->find($user_id);

            $this->assign([
                'list' => $order,
                'bonus_price' => $arr,
                'totalprice' => $totalprice,
                'balance' => $balance
            ]);

            return $this->fetch('dis_index');
        }
        $start_time = strtotime(input('start_time'));
        $end_time = strtotime(input('end_time'));

       if($start_time && $end_time){
           $list = Db::name('order')
               ->alias('o')
               ->where('o.create_time', '>', $start_time)
               ->where('o.create_time', '<', $end_time)
               ->order('o.create_time','desc')
               ->join('order_address oa','oa.order_id = o.order_id')
               ->join('order_goods og','og.order_id = o.order_id')
               ->join('goods_image gi','gi.goods_id = og.goods_id')
               ->join('upload_file uf','uf.file_id = gi.image_id')
               ->field('o.create_time as addtime,o.*,og.*')
               ->paginate(10,false,['query' => Request::instance()->request()]);
       }else if($start_time){
           $list = Db::name('order')
               ->alias('o')
               ->where('o.create_time', '>', $start_time)
               ->order('o.create_time','desc')
               ->join('order_address oa','oa.order_id = o.order_id')
               ->join('order_goods og','og.order_id = o.order_id')
               ->join('goods_image gi','gi.goods_id = og.goods_id')
               ->join('upload_file uf','uf.file_id = gi.image_id')
               ->field('o.create_time as addtime,o.*,og.*')
               ->paginate(10,false,['query' => Request::instance()->request()]);
       }else if($end_time){
           $list = Db::name('order')
               ->alias('o')
               ->where('o.create_time', '<', $end_time)
               ->order('o.create_time','desc')
               ->join('order_address oa','oa.order_id = o.order_id')
               ->join('order_goods og','og.order_id = o.order_id')
               ->join('goods_image gi','gi.goods_id = og.goods_id')
               ->join('upload_file uf','uf.file_id = gi.image_id')
               ->field('o.create_time as addtime,o.*,og.*')
               ->paginate(10,false,['query' => Request::instance()->request()]);
       }else{
           $list = Db::name('order')
               ->alias('o')
               ->order('o.create_time','desc')
               ->join('order_address oa','oa.order_id = o.order_id')
               ->join('order_goods og','og.order_id = o.order_id')
               ->join('goods_image gi','gi.goods_id = og.goods_id')
               ->join('upload_file uf','uf.file_id = gi.image_id')
               ->field('o.create_time as addtime,o.*,og.*')
               ->paginate(10,false,['query' => Request::instance()->request()]);
       }
        $total = 0;
        $no_total = 0;
        foreach($list as $k=>$v){
            if($v['pay_status'] == 20){
                $total += $v['pay_price'];
            }else if($v['pay_status'] == 10){
                $no_total += $v['pay_price'];
            }
        }
       $week = $list = Db::name('order')
           ->whereTime('create_time','week')
           ->select();
        $week_total = 0;
        $week_nototal = 0;
        foreach($week as $zhou){
            if($zhou['pay_status'] == 20){
                $week_total += $zhou['pay_price'];
            }else if($zhou['pay_status'] == 10){
                $week_nototal += $zhou['pay_price'];
            }
        }
       $month = $list = Db::name('order')
            ->whereTime('create_time','month')
           ->select();

        $month_total = 0;
        $month_nototal = 0;
        foreach($month as $yue){
            if($yue['pay_status'] == 20){
                $month_total += $yue['pay_price'];
            }else if($yue['pay_status'] == 10){
                $month_nototal += $yue['pay_price'];
            }
        }
        $year = $list = Db::name('order')
            ->whereTime('create_time','year')
            ->select();
        $year_total = 0;
        $year_nototal = 0;
        foreach($year as $n){
            if($n['pay_status'] == 20){
                $year_total += $n['pay_price'];
            }else if($n['pay_status'] == 10){
                $year_nototal += $n['pay_price'];
            }
        }

        $this->assign([
            'list' => $list,
            'total' => $total,
            'no_total' => $no_total,
            'week_total' => $week_total,
            'week_nototal' => $week_nototal,
            'month_total' => $month_total,
            'month_nototal' => $month_nototal,
            'year_total' => $year_total,
            'year_nototal' => $year_nototal,
            'start_time' => input('start_time'),
            'end_time' => input('end_time')

        ]);
        return $this->fetch();
    }

    public function presentation_money(){

        $user_id = $this->store['user']['store_user_id'];

        $user = Db::name('store_user')->find($user_id);

        $money = input('money');

        if($user['money'] < $money || $money <= 0){
            return $this->return_msg(400,'余额不足，请输入正确金额');
        }



        Db::startTrans();

        try{
            $save = Db::name('store_user')->where('store_user_id',$user_id)->update(['money' => $user['money'] - $money]);

            if($save){
                $res['price'] = $money;
                $res['user_id'] = $user_id;
                $res['addtime'] = time();
                $data = Db::name('presentation')->insert($res);
            }

            Db::commit();
        }catch(\Exception $e){
            Db::rollback();
            return $this->return_msg('400','请求异常');
        }

        if($data){
            return $this->return_msg(200,'申请提现成功');
        }

    }

}