<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/7/9
 * Time: 16:11
 */

namespace app\store\controller;

use think\Db;
use think\Request;
use app\store\controller\goods\Parts;

Class Matter extends Controller{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->auth();
    }
    public function index(){

        $list = Db::name('matter')
            ->alias('m')
            ->join('category_parts cp','cp.category_id = m.cate_id')
            ->field('m.*,cp.name as cate_name')
            ->paginate('10',false,['query' => Request::instance()->request()]);
        return $this->fetch('index',compact('list'));
    }

    public function add(){
        $list = $this->cates();
        $cate = Db::name('category')->where('parent_id',0)->select();

        if(request()->isPost()){
            $res = Request::instance()->param();
            $res['addtime'] = time();

            $data = Db::name('matter')->insert($res);

            if($data){
                return $this->return_msg(200,'成功');
            }else{
                return $this->return_msg(400,'error');
            }
        }
        return $this->fetch('add',compact('cate','list'));
    }

    public function cates(){
        $list = [];
        $num = 1;
        $lists = Db::name('category_parts')->select();
        foreach($lists as $k => $v){
            if($v['parent_id'] != 0){
                $v['num'] = $num++;
                $v['name'] = str_repeat('-- ',$v['num']).$v['name'];
            }
            $list[] = $v;
        }
        return $list;
    }
    public function edit(){
        $id = input('id');
        $list = $this->cates();
        $cate = Db::name('category')->where('parent_id',0)->select();
        $edit = Db::name('matter')
            ->alias('m')
            ->where('m.id',$id)
            ->join('category_parts cp','cp.category_id = m.cate_id')
            ->join('category c','c.category_id = cp.product_cateid')
            ->field('m.*,cp.product_cateid as product_cateid')
            ->find();
//        dump($edit);
        if(request()->isPost()){
            $res = Request::instance()->param();

            $data = Db::name('matter')->update($res);
            if($data){
                return $this->return_msg(200,'成功');
            }else{
                return $this->return_msg(400,'error');
            }


        }
        return $this->fetch('edit',compact('edit','cate','list'));
    }

    public function del(){
        $id = input('id');

//        $info = Db::name('file')->find($id);
//
//        if($info['file']){
//            $url = str_replace('/uploads','uploads',$info['file']);
//            if(file_exists($url)){
//                unlink($url);
//            }
//        }
        $data = Db::name('matter')->delete($id);

        if($data){
            return $this->index();
        }
    }
}