<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/7/18
 * Time: 17:04
 */
namespace app\store\controller;
use think\Db;
use think\Request;

class Presentation extends Controller{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->auth();
    }
    public function index(){

        $list = Db::name('presentation')
            ->alias('p')
            ->order('p.addtime desc')
            ->join('store_user s','s.store_user_id = p.user_id')
            ->field('p.*,s.user_name')
            ->paginate(10,false,['query' => Request::instance()->request()]);

        return $this->fetch('index',compact('list'));
    }

    public function save_status(){

        $id = input('id');

        $info = Db::name('presentation')->find($id);

        if($info['status'] == 0){
            $data = Db::name('presentation')->where('id',$id)->update(['status' => 1]);

            if($data){
                $code = 200;
                $msg = '更新成功';
            }
        }

        return $this->return_msg($code,$msg);
    }
}